app = "sid-checker"

[build]
  builtin = "python"
  
kill_signal = "SIGINT"
kill_timeout = 15

[[services]]
  internal_port = 5000
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    handlers = ["http"]
    port = 80
